/*
 * Copyright Allo authors. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ALLO_PYNQ_ATTRS_H
#define ALLO_PYNQ_ATTRS_H

#include "mlir/IR/Attributes.h"
#include "mlir/IR/DialectImplementation.h"

// Include dialect header for namespace resolution
#include "allo/Dialect/PYNQDialect.h"

// PYNQ enums generated by tablegen
#include "allo/Dialect/PYNQEnums.h.inc"

// PYNQ attributes generated by tablegen
#define GET_ATTRDEF_CLASSES
#include "allo/Dialect/PYNQAttrs.h.inc"

#endif // ALLO_PYNQ_ATTRS_H
