/*
 * Copyright Allo authors. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ALLO_PYNQ_OPS_H
#define ALLO_PYNQ_OPS_H

#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Include dialect and types
#include "allo/Dialect/PYNQDialect.h"
#include "allo/Dialect/PYNQTypes.h"

// PYNQ operations generated by tablegen
#define GET_OP_CLASSES
#include "allo/Dialect/PYNQOps.h.inc"

#endif // ALLO_PYNQ_OPS_H
