/*
 * Copyright Allo authors. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ALLO_PYNQ_DIALECT_H
#define ALLO_PYNQ_DIALECT_H

#include "mlir/IR/Dialect.h"

// PYNQ dialect definition generated by tablegen
#include "allo/Dialect/PYNQDialect.h.inc"

#endif // ALLO_PYNQ_DIALECT_H
