/*
 * Copyright Allo authors. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ALLO_PYNQ_TYPES_H
#define ALLO_PYNQ_TYPES_H

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"

// Include the dialect header for namespace resolution
#include "allo/Dialect/PYNQDialect.h"

// PYNQ types generated by tablegen
#define GET_TYPEDEF_CLASSES
#include "allo/Dialect/PYNQTypes.h.inc"

#endif // ALLO_PYNQ_TYPES_H
