/*
 * Copyright Allo authors. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ALLO_VIVADO_DIALECT_H
#define ALLO_VIVADO_DIALECT_H

#include "mlir/IR/Dialect.h"

// Vivado dialect will be generated by tablegen
#include "allo/Dialect/VivadoDialect.h.inc"

#endif // ALLO_VIVADO_DIALECT_H
